### ISSUE TITLE
"select columns to display" menu items state change is not reported

### ISSUE THREAD

**Issue by burmancomp** [RPTools-org/thunderbirdPlusG5#6]
"Select columns to display" menu items state changes are not currently reported.

If thunderbird app module nameChange event executes somehow focus object stateChange event when user changes state, menu state changes should be automatically reported in speech and braille. There may be more appropriate approaches.

**Comment by burmancomp** [comment]
I have opened [nvda issue](https://github.com/nvaccess/nvda/issues/16323). If they accept issue, and there is no other implementation, then I am about to open pr with that approach. Then if it would be accepted, executing parent class nameChange event could be enough for this issue in thunderbirdplusg5. This is for your information, and maybe there are more appropriate approaches.

**Comment by burmancomp** [comment]
I have opened [pr](https://github.com/nvaccess/nvda/pull/16400) for this.

**Comment by RPTools-org** [comment]
This is a bug in Thunderbird 115.x itself.
To reproduce it:
* Open the menu: Choose the columns to display;
* Check a column by pressing Enter on it;
* Press NVDA+UpArrow to hear the checkbox status;
* You hear that the state has not yet changed;
* Press DownArrow to move to the next column,;
* You now hear the new state of the checkbox;

=> This issue cannot be fixed by Thunderbird+G5 add-on.

**Comment by burmancomp** [comment]
I think this can be fixed by modifying nameChange event in ThunderbirdPlusG5 because it works in NVDA after [pr 16400](https://github.com/nvaccess/nvda/pull/16400) was accepted. If addon is not modified it means unfortunately that this feature is not available when addon is used.

**Comment by burmancomp** [comment]
>  If addon is not modified it means unfortunately that this feature is not available when addon is used.

Sorry. I did not come to think that pr is part of 2024.2 release so it takes some time until it is available in official version of NVDA, which means also that it cannot be utilized in official release of addon until then.
